/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import { useState, useEffect } from 'react'

export function PencilRocket(props) {

  const { nodes, materials } = useGLTF('/PencilRocket.glb')

  const [topColor, setTopColor] = useState(props.topColor) 
  const [middleColor, setMiddleColor] = useState(props.middleColor)
  const [bottomColor, setBottomColor] = useState(props.bottomColor)
  const [legColor, setLegColor] = useState(props.legColor)

  useEffect(() => {
    setTopColor(props.topColor)
  }, [props.topColor])

  useEffect(() => {
    setMiddleColor(props.middleColor)
  }, [props.middleColor])

  useEffect(() => {
    setBottomColor(props.bottomColor)
  }, [props.bottomColor])

  useEffect(() => {
    setLegColor(props.legColor)
  }, [props.legColor])

  return (
    <group {...props} dispose={null}>
      <group position={[0, 3.17, 0]} rotation={[0, 0.21, 0]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Mitte} material-color={middleColor} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.Oben} material-color={topColor} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.Unten} material-color={bottomColor} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials.Füße} material-color={legColor} />
      </group>
    </group>
  )
}

useGLTF.preload('/PencilRocket.glb')
